server:
  port: 8888
  servlet:
    context-path: /es
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    elasticsearch:
      cluster-nodes: 192.168.121.200:9300